In [ ]:
import numpy as np # Scientific computing library

# Project: Homogeneous Transformation Matrices for a 2 DOF Robotic Arm
# Author: Addison Sears-Collins
# Date created: August 11, 2020

# Servo (joint) angles in degrees
servo_0_angle = 45 # Joint 1
servo_1_angle = 30 # Joint 2

# Link lengths in centimeters
a1 = 30 # Length of link 1
a2 = 100 # Length of link 2
a3 = 10 # Length of link 3
a4 = 20 # Length of link 4

# Convert servo angles from degrees to radians
servo_0_angle = np.deg2rad(servo_0_angle)
servo_1_angle = np.deg2rad(servo_1_angle)

# Define the first rotation matrix.
# This matrix helps convert servo_1 frame to the servo_0 frame.
# There is only rotation around the z axis of servo_0.
rot_mat_0_1 = np.array([[np.cos(servo_0_angle), -np.sin(servo_0_angle), 0],
                        [np.sin(servo_0_angle), np.cos(servo_0_angle), 0],
                        [0, 0, 1]])

# Define the second rotation matrix.
# This matrix helps convert the
# end-effector frame to the servo_1 frame.
# There is only rotation around the z axis of servo_1.
rot_mat_1_2 = np.array([[np.cos(servo_1_angle), -np.sin(servo_1_angle), 0],
                        [np.sin(servo_1_angle), np.cos(servo_1_angle), 0],
                        [0, 0, 1]])

# Calculate the rotation matrix that converts the
# end-effector frame to the servo_0 frame.
rot_mat_0_2 = rot_mat_0_1 @ rot_mat_1_2

# Displacement vector from frame 0 to frame 1. This vector describes
# how frame 1 is displaced relative to frame 0.
disp_vec_0_1 = np.array([[a2 * np.cos(servo_0_angle)],
                         [a2 * np.sin(servo_0_angle)],
                         [a1]])

# Displacement vector from frame 1 to frame 2. This vector describes
# how frame 2 is displaced relative to frame 1.
disp_vec_1_2 = np.array([[a4 * np.cos(servo_1_angle)],
                         [a4 * np.sin(servo_1_angle)],
                         [a3]])


# Row vector for bottom of homogeneous transformation matrix
extra_row_homgen = np.array([[0, 0, 0, 1]])

# Create the homogeneous transformation matrix from frame 0 to frame 1
homgen_0_1 = np.concatenate((rot_mat_0_1, disp_vec_0_1), axis=1) # side by side
homgen_0_1 = np.concatenate((homgen_0_1, extra_row_homgen), axis=0) # one above the other

# Create the homogeneous transformation matrix from frame 1 to frame 2
homgen_1_2 = np.concatenate((rot_mat_1_2, disp_vec_1_2), axis=1)
homgen_1_2 = np.concatenate((homgen_1_2, extra_row_homgen), axis=0)

# Calculate the homogeneous transformation matrix from frame 0 to frame 2
homgen_0_2 = homgen_0_1 @ homgen_1_2

# Display the homogeneous transformation matrix
print("Homogeneous Transformation Matrix from Frame 0 to Frame 2")
print(homgen_0_2)

Homogeneous Transformation Matrix from Frame 0 to Frame 2
[[ 0.25881905 -0.96592583  0.         75.88705902]
 [ 0.96592583  0.25881905  0.         90.02919464]
 [ 0.          0.          1.         40.        ]
 [ 0.          0.          0.          1.        ]]


In [ ]:
import numpy as np # Scientific computing library

# Project: Calculating Rotation Matrices
# Author: Addison Sears-Collins
# Date created: August 1, 2020

# Servo (joint) angles in degrees
servo_0_angle = 45 # Joint 1
servo_1_angle = 30 # Joint 2
servo_2_angle = -30 # Joint 2

# Link lengths in centimeters
a1 = 30 # Length of link 1
a2 = 100 # Length of link 2
a3 = 20 # Length of link 3

# Convert servo angles from degrees to radians
servo_0_angle = np.deg2rad(servo_0_angle)
servo_1_angle = np.deg2rad(servo_1_angle)
servo_2_angle = np.deg2rad(servo_2_angle)

# Define the first rotation matrix.
# This matrix helps convert frame 1 to frame 0.
# There is only rotation around the z axis of servo_0.
rot_mat_0_1 = np.array([[np.cos(servo_0_angle), 0, np.sin(servo_0_angle)],
                        [np.sin(servo_0_angle), 0, -np.cos(servo_0_angle)],
                        [0, 1, 0]])

# Define the second rotation matrix.
# This matrix helps convert the
# end-effector frame (frame 2) to frame 1.
# There is only rotation around the z axis of servo_1 (joint 2).
rot_mat_1_2 = np.array([[np.cos(servo_1_angle), -np.sin(servo_1_angle), 0],
                        [np.sin(servo_1_angle), np.cos(servo_1_angle), 0],
                        [0, 0, 1]])

rot_mat_2_3 = np.array([[np.cos(servo_2_angle), -np.sin(servo_2_angle), 0],
                        [np.sin(servo_2_angle), np.cos(servo_2_angle), 0],
                        [0, 0, 1]])

# Calculate the rotation matrix that converts the
# end-effector frame to the servo_0 frame.
rot_mat_0_3 = rot_mat_0_1 @ rot_mat_1_2 @ rot_mat_2_3


disp_vec_0_1 = np.array([[0],
                         [0],
                         [a1]])

disp_vec_1_2 = np.array([[a2 * np.cos(servo_1_angle)],
                         [a2 * np.sin(servo_1_angle)],
                         [0]])

disp_vec_2_3 = np.array([[a3 * np.cos(servo_2_angle)],
                         [a3 * np.sin(servo_2_angle)],
                         [0]])

# Row vector for bottom of homogeneous transformation matrix
extra_row_homgen = np.array([[0, 0, 0, 1]])

# Create the homogeneous transformation matrix from frame 0 to frame 1
homgen_0_1 = np.concatenate((rot_mat_0_1, disp_vec_0_1), axis=1) # side by side
homgen_0_1 = np.concatenate((homgen_0_1, extra_row_homgen), axis=0) # one above the other

# Create the homogeneous transformation matrix from frame 1 to frame 2
homgen_1_2 = np.concatenate((rot_mat_1_2, disp_vec_1_2), axis=1)
homgen_1_2 = np.concatenate((homgen_1_2, extra_row_homgen), axis=0)

# Create the homogeneous transformation matrix from frame 1 to frame 2
homgen_2_3 = np.concatenate((rot_mat_2_3, disp_vec_2_3), axis=1)
homgen_2_3 = np.concatenate((homgen_2_3, extra_row_homgen), axis=0)

# Calculate the homogeneous transformation matrix from frame 0 to frame 2
homgen_0_3 = homgen_0_1 @ homgen_1_2 @ homgen_2_3

# Display the homogeneous transformation matrix
print(homgen_0_3)

[[ 7.07106781e-01 -2.14765645e-17  7.07106781e-01  7.53793792e+01]
 [ 7.07106781e-01 -2.89136486e-17 -7.07106781e-01  7.53793792e+01]
 [-7.43708407e-18  1.00000000e+00  0.00000000e+00  8.00000000e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
