<a href="https://colab.research.google.com/github/josepedroso/projetos_colab/blob/main/t1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from skimage.feature import hog
from skimage import exposure
import cv2
import os
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [ ]:
def cria_dados():
  x_data = []
  y_data = []
  arquivo = '/digits/files.txt'

  with open(arquivo, 'r') as f:
        linhas = f.readlines()
        for num_linha, linha in enumerate(linhas, 0):
                parts = linha.split(" ")
                x_data.append(parts[0])
                y_data.append(parts[1].replace("\n", ""))
  return x_data, y_data

In [ ]:
def extracted_fetures(name_img):
  img = cv2.imread(name_img, cv2.IMREAD_GRAYSCALE)
  img_resize = cv2.resize(img, (40, 40))
  # Aplicar o threshold binário
  # threshold_value = 128  # Valor de limite (pode ser ajustado)
  #_, binary_image = cv2.threshold(img_resize, threshold_value, 255, cv2.THRESH_BINARY)

  feature_vector, hog_image = hog(img_resize, orientations=8, pixels_per_cell=(16, 16),
                                cells_per_block=(1, 1), visualize=True, block_norm='L2-Hys')

  return    feature_vector

In [ ]:
path_images = '/content/drive/MyDrive/digits/'

x_dataset_paths, y_dataset = cria_dados()
x_dataset = []

for index, img_name in enumerate(x_dataset_paths, 0):
  feature_vector = extracted_fetures(path_images + img_name)
  x_dataset.append(feature_vector)


X_train, X_test, y_train, y_test = train_test_split(x_dataset, y_dataset, test_size=0.3, random_state=42)

In [ ]:
# Train kNN
classifier = KNeighborsClassifier(n_neighbors=10)
classifier.fit(X_train, y_train)

# Make predictions
y_pred = classifier.predict(X_test)

# Compute metrics
acuracia = accuracy_score(y_test, y_pred)
matriz_confusao = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred, output_dict=True)

# Call the function and print results
print("Acurácia:", acuracia)
print("Matriz de Confusão:", matriz_confusao)
print("Relatório de Classificação:", report)

Acurácia: 0.8066666666666666
Matriz de Confusão: [[46  0  2  0  0  0  2  0  1  1]
 [ 5 57  5  1  0  0  0  0  1  0]
 [ 0  2 52  5  5  0  1  3  3  1]
 [ 1  0  2 36  0  6  0  0  9  1]
 [ 0  1  1  1 45  0  0  0  2  4]
 [ 2  1  0  4  1 37  1  0  3  0]
 [ 8  1  0  1  2  0 45  0  0  0]
 [ 2  0  0  0  0  0  0 55  1  4]
 [ 2  2  0  4  1  2  1  0 52  0]
 [ 3  0  0  2  0  0  0  2  0 59]]
Relatório de Classificação: {'0': {'precision': 0.6666666666666666, 'recall': 0.8846153846153846, 'f1-score': 0.7603305785123966, 'support': 52}, '1': {'precision': 0.890625, 'recall': 0.8260869565217391, 'f1-score': 0.8571428571428571, 'support': 69}, '2': {'precision': 0.8387096774193549, 'recall': 0.7222222222222222, 'f1-score': 0.7761194029850746, 'support': 72}, '3': {'precision': 0.6666666666666666, 'recall': 0.6545454545454545, 'f1-score': 0.6605504587155963, 'support': 55}, '4': {'precision': 0.8333333333333334, 'recall': 0.8333333333333334, 'f1-score': 0.8333333333333334, 'support': 54}, '5': {'precision

In [ ]:
#cria arquivo com as features
path_images = '/digits/'
out_file_name = "allFeatures.txt"
output_file = open(out_file_name, 'w')

x_dataset, y_dataset = cria_dados()

for index, img_name in enumerate(x_dataset, 0):

  normalized_feature_vector = extracted_fetures(path_images + img_name)

  for value in normalized_feature_vector:
        output_file.write(f'{value}  ')

  output_file.write(f'{y_dataset[index]}')
  output_file.write(f'\n')